version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: bbgon
      POSTGRES_PASSWORD: '!@QWASZX'
      POSTGRES_DB: cas
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cas
      SPRING_DATASOURCE_USERNAME: bbgon
      SPRING_DATASOURCE_PASSWORD: '!@QWASZX'
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
